version: "2"

services:
  storage:
    image: openzipkin/zipkin-mysql
    container_name: zipkin-playground-mysql
    environment:
      - MYSQL_HOST=mysql

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin-playground-zipkin
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=zipkin-playground-mysql
    ports:
      - 9411:9411
    depends_on:
      - storage

  data-service:
    build: ./data-service
    ports:
      - "3001:3001"
    depends_on:
      - zipkin

  # auth-service:
  #   build: ./auth-service
  #   ports:
  #     - "3002:3002"

  web-service:
    build: ./web-service
    ports:
      - "3000:3000"
    depends_on:
      - data-service
      - zipkin
