version: "2"

services:
  storage:
    image: openzipkin/zipkin-mysql
    container_name: zipkin-playground-mysql
    environment:
      - MYSQL_HOST=mysql

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin-playground-zipkin
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=zipkin-playground-mysql
    ports:
      - 9411:9411
    depends_on:
      - storage

  date-service:
    build: ./date-service
    ports:
      - "3001:3001"
    depends_on:
      - zipkin
    environment:
      - ZIPKIN_ENDPOINT=http://zipkin:9411
      - SERVICE_NAME=date-service
      - PORT=3001

  auth-service:
    build: ./auth-service
    ports:
      - "3002:3002"
    depends_on:
      - zipkin
      - date-service
    environment:
      - ZIPKIN_ENDPOINT=http://zipkin:9411
      - SERVICE_NAME=auth-service
      - DATE_SERVICE_ENDPOINT=http://date-service:3001
      - PORT=3002

  web-service:
    build: ./web-service
    ports:
      - "3000:3000"
    depends_on:
      - date-service
      - zipkin
      - auth-service
    environment:
      - ZIPKIN_ENDPOINT=http://zipkin:9411
      - DATE_SERVICE_ENDPOINT=http://date-service:3001
      - AUTH_SERVICE_ENDPOINT=http://auth-service:3002
      - SERVICE_NAME=web-service
      - PORT=3000
